apiVersion: v1
kind: Pod
metadata:
  name: test1
  namespace: training
spec:
  imagePullSecrets:
    - name: ecr-secret

  containers:
    - name: login-app
      image: 797894062399.dkr.ecr.us-east-1.amazonaws.com/login-app:latest
      imagePullPolicy: Always
